Monitor Service loadavg
kubos/kubos pull request #591
Opened 2022-12-19 08:25 UTC by Ropes

Implemented a reader and parser service of /proc/loadavg which is
accessible via GraphQL `loadavg` request. Returned as the
LoadAvgResponse.

2022-12-22 17:42 UTC, marshall commented
love this

2022-12-22 17:59 UTC, marshall requested changes
looks great! I left a few suggestions that will make your code a bit more compact and some rust pointers too :)

my only real concern is what looks like unnecessary calls to `map` all over `monitor-service/src/objects.rs`, that aren't necessarily your fault but I'm wondering why the pattern even exists. lmk what you think the best next step is there..

2022-12-22 17:59 UTC, marshall commented on docs/ecosystem/services/monitor-service.rst
> +
great docs, thank you!

2022-12-22 17:59 UTC, marshall commented on services/monitor-service/src/loadavg.rs
> +        }
just a minor suggestion -- since you already derive `Default`, and the implementation provides None for all `Option` types, you can use it to save quite a bit of work here..
```suggestion
        Default::default()
```

2022-12-22 17:59 UTC, marshall commented on services/monitor-service/src/loadavg.rs
> +        }
```suggestion
        avg.parse().ok()
```

2022-12-22 17:59 UTC, marshall commented on services/monitor-service/src/loadavg.rs
> +        }
```suggestion
        s.parse().ok()
```

2022-12-22 17:59 UTC, marshall commented on services/monitor-service/src/loadavg.rs
> +        }
similar to above, you may not actually want/need these helpers :)

2022-12-22 17:59 UTC, marshall commented on services/monitor-service/src/loadavg.rs
> +mod tests {
\o/ tests

2022-12-22 17:59 UTC, marshall commented on services/monitor-service/src/loadavg.rs
> +        let info: Result<LoadAvg, failure::Error> = LoadAvg::parse(RAW0);
FYI, I think this explicit type here is unnecessary.

2022-12-22 17:59 UTC, marshall commented on services/monitor-service/src/objects.rs
> +});
I know you're following the example of other code in this file, but my radar is up -- it feels like this map conversion is unnecessary. does your code still work if you simply return the raw `Option<f64>` without mapping? it seems like it should

2022-12-22 17:59 UTC, marshall commented on services/monitor-service/src/schema.rs
> +            .map(|avgs| LoadAvgResponse{ avgs })
nit: space after `LoadAvgResponse`. I think `cargo fmt` should've caught that though hm

2022-12-22 18:02 UTC, marshall commented on services/monitor-service/src/objects.rs
> +});
I also acknowledge that this is wrapped into a somewhat magic macro, which could be using these map statements as type declarations.. so wasn't 100% certain about it

2022-12-22 18:18 UTC, Ropes commented on services/monitor-service/src/loadavg.rs
> +        }
That is some fantastic magic macros!

2022-12-22 18:22 UTC, Ropes commented on services/monitor-service/src/loadavg.rs
> +        }
SO much Rust magic to learn.

2022-12-22 18:23 UTC, Ropes commented on services/monitor-service/src/schema.rs
> +            .map(|avgs| LoadAvgResponse{ avgs })
clippy is sleeping on the job!

2022-12-23 02:57 UTC, marshall submitted a review, later dismissed

2022-12-23 15:52 UTC, Ropes commented on services/monitor-service/src/loadavg.rs
> +        let info: Result<LoadAvg, failure::Error> = LoadAvg::parse(RAW0);
good catch!

2022-12-23 15:52 UTC, Ropes commented on services/monitor-service/src/objects.rs
> +});
You're right, I copy-pasta'd then modified this somewhat confusing object conversion. The `f64` values can just return the Option<f64> without the extra map()!

I tried to play with different options of unpacking the u64, then converting without using the map(), but it ended up worse I think, this was the cleanest other implementation I came up with(which is messier IMO):

```rust
Some(self.avgs.processes_active().unwrap_or_else(|| 0) as f64)
```

Given that within the `loadavg` module, keeping the struct fields as integers makes more sense, I think it's fine to convert them here with a map() since GraphQL is the one forcing it be a float?

2023-01-02 23:18 UTC, marshall approved these changes
looks great!

2023-01-02 23:21 UTC, marshall commented on services/monitor-service/src/objects.rs
> +});
yeah, good catch -- I didn't realize some of the fields were `u64` :)

in that case, the map makes total sense!

2023-01-03 00:01 UTC, merged