Cratesio publish
kubos/kubos pull request #600
Opened 2023-01-18 20:16 UTC by Ropes

rebased #597 to solve Dockerfile conflict. Opening PR to run CI.

Verification needed:
* [ ] kubos-dev docker image

## Original PR

This PR makes it much more straight forward to build a KubOS service out-of-tree by using built in Cargo dependency management and publishing some of Kubos' high level crates to crates.io.

Currently this PR is focused on only publishing these crates:

    kubos-app
    kubos-comms (formerly comms-service)
    kubos-system
    kubos-service
    kubos-telemetry-db

2023-01-18 21:03 UTC, marshall requested changes
it looks like the Dockerfile got a bit reverted in the rebase, I think because this was based on an older version. I marked the differences we need in the Dockerfile

2023-01-18 21:03 UTC, marshall commented on tools/dist/Dockerfile
> +
remove this

2023-01-18 21:06 UTC, Ropes commented on tools/dist/Dockerfile
> +RUN wget https://s3.amazonaws.com/kubos-world-readable-assets/iobc_toolchain.tar.gz && tar -xf ./iobc_toolchain.tar.gz -C /usr/bin && rm ./iobc_toolchain.tar.gz
Got it.

2023-02-02 18:19 UTC, Ropes commented
I think we should decide yay or nay on these changes. We've both run into issues compiling that Cross hasn't solved, but the configuration updates are still steps forward.(I think)

2023-02-21 19:26 UTC, marshall approved these changes
sorry for letting this fester!

2023-02-21 19:32 UTC, merged